### ISSUE TITLE
Crash When Loading up Minecraft

### ISSUE THREAD

**Issue by EchoEarth** [al132mc/A-Lib#1]
When you launch Minecraft I have got it narrowed down to it being a problem with Alib, when launching Minecraft it crashes the game mid load up and says: 
The game crashed whilst initializing game
Error: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
Exit Code: -1
When not having Alib in my mods folder the game loads up totally fine for me this is for Minecraft 1.16.3 and Forge version 1.16.3-34.1.17

**Comment by ghost** [comment]
Could you provide a full log please?

**Comment by EchoEarth** [comment]
Yes here you go

[crash-2020-10-12_18.40.26-client.txt](https://github.com/al132mc/A-Lib/files/5368115/crash-2020-10-12_18.40.26-client.txt)

**Comment by EchoEarth** [comment]
Ok I just took a long look at the code and could it have to do with not dedicating enough ram to Minecraft I already dedicate 10 GB and I have 16 GB of ram should I go up to like 11 or 12 GB?

**Comment by EchoEarth** [comment]
Nevermind just tried that and it still crashed.

**Comment by ghost** [comment]
As best as I can tell this crash doesn't have anything to do with A Lib, nor does it have anything to do with your allocated RAM. It seems like the mod gamestages or bookshelf is causing it. If you have gamestages, it looks like it requires Bookshelf, so please make sure you also have that. If you are having further issues take it up with the author of those mods.

**Comment by EchoEarth** [comment]
Ok great thanks for all your help.
