### ISSUE TITLE
1.19.2 Update Error

### ISSUE THREAD

**Issue by Sonifluous** [al132mc/A-Lib#5]
I recently updated my AlchemyLib mod and noticed that the update is for 1.18 and not for 1.19, it was probably a mix-up and that's ok, just wanted to give y'all a heads up! :3

**Comment by Dark-Arcana** [comment]
I've been pushing out so many updates between so many versions that this was bound to happen. Which version specifically?

**Comment by Sonifluous** [comment]
It's on 1.19.2 Forge, also take care of yourself!!

**Comment by AndreAugustoDev** [comment]
> I've been pushing put so many updates between so many versions that this was bound to happen. Which version specifically?

@Dark-Arcana  `alchemylib-1.18.2-1.0.22.jar`
https://www.curseforge.com/minecraft/mc-mods/alchemylib/files/4655485

**Comment by Dark-Arcana** [comment]
I've removed 1.19.2 as a supported version for that file. Thank you so much for the info.

**Comment by ColonelGerdauf** [comment]
This is odd, as despite the update going through on CurseForge, external launchers are still registering the 1.18 update as the latest update for 1.19.2.

**Comment by ColonelGerdauf** [comment]
I get this every time I try to update mods in a 1.19.2 instance, even well after the version info was fixed on the CurseForge side
![image](https://github.com/SmashingMods/AlchemyLib/assets/6895655/c4e771a9-733d-4d36-b92d-cf957fdb3c92)
