### ISSUE TITLE
Curseforge update issue

### ISSUE THREAD

**Issue by DraTrav** [al132mc/A-Lib#6]
#5 is still currently a problem even after removing it from the supported list.

**Comment by ColonelGerdauf** [comment]
I can suggest uploads to Modrinth. Asides from general benefits to users and modmakers, it is much more straightforward, and much quicker, to resolve these kinds of versioning errors.

**Comment by ColonelGerdauf** [comment]
This issue appears to be finally resolved on updaters.

**Comment by Dark-Arcana** [comment]
I'm not going to upload to Modrinth. But someone was able to refresh the cache over at CurseForge.
